version: "3"

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraft
    user: '1000:1000'
    restart: unless-stopped
    environment:
      EULA: "true"
      TYPE: FABRIC
      MEMORY: 2G
      OVERRIDE_SERVER_PROPERTIES: false
      CREATE_CONSOLE_IN_PIPE: true
      MODRINTH_PROJECTS: fabric-api,ferrite-core,krypton,lithium,sodium
      ENABLE_RCON: false
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
